name: WatchTowerGui
version: 1.0
main: watchtowergui.wg.WatchTowerGui
description: Manage your server in the easiest way!
authors: [ Devie, DJKK12 ]
softdepend: [ UltimateGuis ]
commands:
  gluday:
    usage: /gluday
    description: Get Logs From Day By UUID
    permission: watchTowerGui.commands.admin.gluday
  gludate:
    usage: /gldate
    description: Get Logs From Date Interval By UUID
    permission: watchTowerGui.commands.admin.gludate
  glday:
    usage: /glday
    description: Get Logs From Day
    permission: watchTowerGui.commands.admin.glday
  gldate:
    usage: /gldate
    description: Get Logs From Date Interval
    permission: watchTowerGui.commands.admin.gldate
  mmode:
    usage: /mmode
    description: turn ON / OFF Maintenance Mode
    permission: watchTowerGui.commands.admin.maintenancePerm
  unmute:
    usage: /unmute [player]
    description: unmute player
    permission: watchTowerGui.commands.admin.unmute
  mute:
    usage: /mute [player]
    description: mute player
    permission: watchTowerGui.commands.admin.mute
  tmunban:
    usage: /tmunban
    description: unban player
    permission: watchTowerGui.commands.admin.tmunban
  tmban:
    usage: /tmban [player]
    description: ban player
    permission: watchTowerGui.commands.admin.tmban
  ad:
    usage: /ad
    description: admin interface
    permission: watchTowerGui.commands.admin.ad
  freeze:
    usage: /freeze [player]
    description: freeze or unfreeze player
    permission: watchTowerGui.commands.admin.freeze
  playerMenu:
    usage: /playerMenu [player]
    description: open player edit menu
    permission: watchTowerGui.commands.admin.playerMenu
  hide:
    usage: /hide <player>
    description: hide yourself or another player
    permission: watchTowerGui.commands.admin.hideplayer
  sudo:
    usage: /sudo [player] [command_and_arguments]
    description: execute command as another player
    permission: watchTowerGui.commands.admin.sudo
  pluginmenu:
    usage: /pluginmenu <plugin>
    description: open gui with information about given plugin, note that plugin_name is case sensitive
    permission: watchTowerGui.commands.admin.pluginmenu
  commandmenu:
    usage: /commandmenu <command_name>
    description: open gui with tools for given enabled command
    permission: watchTowerGui.commands.admin.commandmenu
  resetAllCommands:
    usage: /resetallcommands
    description: reset commands settings like aliases and labels to default
    permission: watchTowerGui.commands.admin.resetallcommands
  test:
    usage: /test
    description: test
    permission: watchTowerGui.commands.admin.test