name: Build Jars

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.5.1
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots clean install
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Built-JARS
          path: staging